name: 'minio upload'
description: 'upload directory to s3-compatible storage'
inputs:
  host:
    description: 'MINIO_SERVER_HOST'
    required: true
  scheme:
    description: 'MINIO_SERVER_SCHEME'
    required: true
  port:
    description: 'MINIO_SERVER_PORT'
    required: true
  access_key:
    description: 'MINIO_ACCESS_KEY'
    required: true
  secret_key:
    description: 'MINIO_SECRET_KEY'
    required: true
  bucket:
    description: 'target bucket'
    required: true
  source_dir:
    description: 'source directory'
    required: false
    default: 'public'
  target_dir:
    description: 'target directory'
    required: false
    default: '/'
runs:
  using: 'docker'
  image: docker.io/bitnami/minio-client:latest
  env:
    MINIO_SERVER_HOST: ${{ inputs.host }}
    MINIO_SERVER_SCHEME: ${{ inputs.scheme }}
    MINIO_SERVER_PORT: ${{ inputs.port }}
    MINIO_SERVER_ACCESS_KEY: ${{ inputs.access_key }}
    MINIO_SERVER_SECRET_KEY: ${{ inputs.secret_key }}
  args:
    - mirror
    - --overwrite
    - "{{ inputs.source_dir }}"
    - "minio/${{ inputs.bucket }}${{ inputs.target_dir }}"
