name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install

      - name: Build
        run: |
          npm run build

      - name: Upload static HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-html
          path: dist/

  deploy-pr-preview:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: pr-previews
      url: "https://sgc-dashboard-preview-d98d665658f0.s3-eu-central-2.ionoscloud.com/pr/${{github.event.number}}/${{github.event.pull_request.head.sha}}/index.html"
    steps:
      - uses: actions/checkout@v4
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist
      - name: Upload website to S3
        uses: ./.github/actions/minio-upload
        with:
          url: "https://s3-eu-central-2.ionoscloud.com"
          accessKey:  ${{ secrets.S3_ACCESS_KEY }}
          secretKey:  ${{ secrets.S3_SECRET_KEY }}
          bucket: sgc-dashboard-preview-d98d665658f0
          source_dir: dist/
          target_dir: /pr/${{ github.event.number }}/${{github.event.pull_request.head.sha}}

  deploy-main-to-branch:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist
      - name: Deploy to branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: dist
          single-commit: true

  deploy-main-to-prod:
    needs: deploy-main-to-branch
    runs-on: ubuntu-latest
    steps:
      - name: Call PROD_DEPLOY_WEBHOOK
        run: |
          curl -X POST ${{ secrets.PROD_DEPLOY_WEBHOOK }}

  deploy-main-to-gh-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
