name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Use Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install
        
    - name: Build
      run: |
        npm run build

    - name: Upload static HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-html
        path: dist/
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: .
      - name: Debug ls
        run: ls -la
      - name: Upload website to S3
        uses: ./.github/actions/minio-upload
        with:
          endpoint:  ${{ secrets.S3_ENDPOINT }}
          acces_key:  ${{ secrets.S3_ACCESS_KEY }}
          secret_key:  ${{ secrets.S3_SECRET_KEY }}
          bucket: github-dashboard-ci
          source_dir: .
          target_dir: /
