name: Build and deploy main branch

on:
  push:
    branches: [ "main" ]
  # uncomment the following two lines while developing the CI
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        run: |
          devenv shell npm run build

      - name: Upload static HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-html
          path: dist/

  deploy-main-to-branch:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist
      - name: Deploy to branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: dist
          single-commit: true

  deploy-main-to-prod:
    needs: deploy-main-to-branch
    runs-on: ubuntu-latest
    steps:
      - name: Call PROD_DEPLOY_WEBHOOK
        run: |
          curl -X POST ${{ secrets.PROD_DEPLOY_WEBHOOK }}

  deploy-main-to-gh-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
